version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jshub_api
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DB_URI=mongodb://mongo:27017/jshub
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: jshub_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db_data/:/data/db
