version: '3.8'

services:
  api:
    image: dkowalski1997/jshub
    container_name: jshub_api
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DB_URI=mongodb://root:t4jn3h4slo@mongo:27017/jshub
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: jshub_db
    environment:
      - MONGO_INITDB_DATABASE=jshub
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=t4jn3h4slo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db_data/:/data/db
