name: deploy

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: dkowalski1997/jshub

jobs:
  build_docker_images:
    name: Build images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t $DOCKER_IMAGE_NAME .

      - name: Push image
        run: |
          docker login -u dkowalski1997 -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push $DOCKER_IMAGE_NAME
